{{ if .Values.server.config.daily_reboot.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.server.config.daily_reboot.serviceAccount }}
  namespace: {{ .Values.namespace }}
{{ end }}